"""empty message

Revision ID: 10f6d839ce80
Revises: 2874b3bd80fa
Create Date: 2015-06-21 16:48:46.280406

"""

# revision identifiers, used by Alembic.
revision = '10f6d839ce80'
down_revision = '2874b3bd80fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dua', sa.Column('is_live', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dua', 'is_live')
    ### end Alembic commands ###
