"""empty message

Revision ID: 22fbd5f2e6ec
Revises: 38395b696f81
Create Date: 2015-06-14 04:56:28.459470

"""

# revision identifiers, used by Alembic.
revision = '22fbd5f2e6ec'
down_revision = '38395b696f81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hadith',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hadith_date_created'), 'hadith', ['date_created'], unique=False)
    op.create_index(op.f('ix_hadith_last_updated'), 'hadith', ['last_updated'], unique=False)
    op.alter_column(u'mosque', 'prayer_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'mosque', 'prayer_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_hadith_last_updated'), table_name='hadith')
    op.drop_index(op.f('ix_hadith_date_created'), table_name='hadith')
    op.drop_table('hadith')
    ### end Alembic commands ###
