"""empty message

Revision ID: 2874b3bd80fa
Revises: 3ace30a2942b
Create Date: 2015-06-21 13:35:47.471545

"""

# revision identifiers, used by Alembic.
revision = '2874b3bd80fa'
down_revision = '3ace30a2942b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mosque_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mosque_id'], ['mosque.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_date_created'), 'event', ['date_created'], unique=False)
    op.create_index(op.f('ix_event_last_updated'), 'event', ['last_updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_last_updated'), table_name='event')
    op.drop_index(op.f('ix_event_date_created'), table_name='event')
    op.drop_table('event')
    ### end Alembic commands ###
