"""empty message

Revision ID: 38395b696f81
Revises: 4988854f3e55
Create Date: 2015-05-29 16:53:21.094081

"""

# revision identifiers, used by Alembic.
revision = '38395b696f81'
down_revision = '4988854f3e55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
