"""empty message

Revision ID: 3ace30a2942b
Revises: 54e40f1d1747
Create Date: 2015-06-20 11:21:58.993343

"""

# revision identifiers, used by Alembic.
revision = '3ace30a2942b'
down_revision = '54e40f1d1747'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_date_created'), 'banner', ['date_created'], unique=False)
    op.create_index(op.f('ix_banner_last_updated'), 'banner', ['last_updated'], unique=False)
    op.create_table('dua',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dua_date_created'), 'dua', ['date_created'], unique=False)
    op.create_index(op.f('ix_dua_last_updated'), 'dua', ['last_updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dua_last_updated'), table_name='dua')
    op.drop_index(op.f('ix_dua_date_created'), table_name='dua')
    op.drop_table('dua')
    op.drop_index(op.f('ix_banner_last_updated'), table_name='banner')
    op.drop_index(op.f('ix_banner_date_created'), table_name='banner')
    op.drop_table('banner')
    ### end Alembic commands ###
