"""empty message

Revision ID: 4988854f3e55
Revises: 19a8aa36b1b1
Create Date: 2015-05-29 16:42:37.529016

"""

# revision identifiers, used by Alembic.
revision = '4988854f3e55'
down_revision = '19a8aa36b1b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_country_date_created'), 'country', ['date_created'], unique=False)
    op.create_index(op.f('ix_country_last_updated'), 'country', ['last_updated'], unique=False)
    op.create_table('prayer_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_prayer_type_date_created'), 'prayer_type', ['date_created'], unique=False)
    op.create_index(op.f('ix_prayer_type_last_updated'), 'prayer_type', ['last_updated'], unique=False)
    op.create_table('sect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sect_date_created'), 'sect', ['date_created'], unique=False)
    op.create_index(op.f('ix_sect_last_updated'), 'sect', ['last_updated'], unique=False)
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_state_date_created'), 'state', ['date_created'], unique=False)
    op.create_index(op.f('ix_state_last_updated'), 'state', ['last_updated'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('encrypted_password', sa.String(length=200), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('sect_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['sect_id'], ['sect.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_date_created'), 'user', ['date_created'], unique=False)
    op.create_index(op.f('ix_user_last_updated'), 'user', ['last_updated'], unique=False)
    op.create_table('mosque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sect_id', sa.Integer(), nullable=True),
    sa.Column('prayer_type_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['prayer_type_id'], ['prayer_type.id'], ),
    sa.ForeignKeyConstraint(['sect_id'], ['sect.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mosque_date_created'), 'mosque', ['date_created'], unique=False)
    op.create_index(op.f('ix_mosque_last_updated'), 'mosque', ['last_updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mosque_last_updated'), table_name='mosque')
    op.drop_index(op.f('ix_mosque_date_created'), table_name='mosque')
    op.drop_table('mosque')
    op.drop_index(op.f('ix_user_last_updated'), table_name='user')
    op.drop_index(op.f('ix_user_date_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_state_last_updated'), table_name='state')
    op.drop_index(op.f('ix_state_date_created'), table_name='state')
    op.drop_table('state')
    op.drop_index(op.f('ix_sect_last_updated'), table_name='sect')
    op.drop_index(op.f('ix_sect_date_created'), table_name='sect')
    op.drop_table('sect')
    op.drop_index(op.f('ix_prayer_type_last_updated'), table_name='prayer_type')
    op.drop_index(op.f('ix_prayer_type_date_created'), table_name='prayer_type')
    op.drop_table('prayer_type')
    op.drop_index(op.f('ix_country_last_updated'), table_name='country')
    op.drop_index(op.f('ix_country_date_created'), table_name='country')
    op.drop_table('country')
    ### end Alembic commands ###
