"""empty message

Revision ID: 54e40f1d1747
Revises: 22fbd5f2e6ec
Create Date: 2015-06-14 05:11:53.013953

"""

# revision identifiers, used by Alembic.
revision = '54e40f1d1747'
down_revision = '22fbd5f2e6ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadith', sa.Column('is_verified', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hadith', 'is_verified')
    ### end Alembic commands ###
